### ISSUE TITLE
Fix up $input reference for PHP 8

### ISSUE THREAD

**Issue by geek-boy** [geek-boy/sumologic-cli#11]
When running the code for PHP 8 the following error occurs when attempting to download messages: 

```
PHP Fatal error:  Uncaught TypeError: Symfony\Component\Console\Helper\QuestionHelper::ask(): Argument #1 ($input) must be of type Symfony\Component\Console\Input\InputInterface, null given, called in /Users/mark.corben/Projects/sumologic-cli/src/Command/QueryRunCommand.php on line 648 and defined in /Users/mark.corben/Projects/sumologic-cli/vendor/symfony/console/Helper/QuestionHelper.php:48
Stack trace:
#0 /Users/mark.corben/Projects/sumologic-cli/src/Command/QueryRunCommand.php(648): Symfony\Component\Console\Helper\QuestionHelper->ask(NULL, Object(Symfony\Component\Console\Output\ConsoleOutput), Object(Symfony\Component\Console\Question\ConfirmationQuestion))
#1 /Users/mark.corben/Projects/sumologic-cli/src/Command/QueryRunCommand.php(478): App\Command\QueryRunCommand->saveQueryResults(Object(Symfony\Component\Console\Output\ConsoleOutput), '3A888A79A7F3A39...', 31, 0, 10000, 'json', 'messages')
#2 /Users/mark.corben/Projects/sumologic-cli/vendor/symfony/console/Command/Command.php(256): App\Command\QueryRunCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/mark.corben/Projects/sumologic-cli/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

Example command that produces error:

```
./sumologic-cli query:run --search-query="amplife.php-errors \"2021-09-09T23:24:35\"" --start="-6days" --end="now"
```

**Comment by geek-boy** [comment]
Fixed up in https://github.com/geek-boy/sumologic-cli/commit/eca5540610e2b356e0725aa1af344375851d58f2
